import Head from 'next/head'
import Image from 'next/image'
import { GetStaticPaths, GetStaticProps } from 'next/types'
import { formatYear } from '../../lib/helpers/date';
import SiteHeader from '../../components/SiteHeader'
import Meta from '../../components/Meta';
import Credits from '../../components/Credits';

export interface TVData {
  tv: {
    name: string;
    overview: string;
    tagline: string;
    backdrop_path: string;
    poster_path: string;
    vote_average: number;
    episode_run_time: Array<number>;
    genres: [{
      id: number;
      name: string;
    }];
    first_air_date: string;
  },
  credits: {}
}

const Movie = ({ tv, credits }: TVData) => {
  return (
    <div>
      <Head>
        <title>NextJs Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto mt-10 max-w-7xl">
        <SiteHeader />

        <header className="relative w-full overflow-hidden h-96">
          <Image
            src={`https://image.tmdb.org/t/p/original${tv.backdrop_path}`}
            alt=""
            layout="raw"
            width={1920}
            height={720}
            className="absolute inset-0 object-cover"
          />
        </header>

        <div className="flex max-w-5xl mx-auto">
          <div className="relative z-20 flex-shrink-0 -mt-14 w-52">
            <Image
              src={`https://image.tmdb.org/t/p/original${tv.poster_path}`}
              alt=""
              layout="raw"
              width={220}
              height={330}
            />
            <div className="flex items-end justify-center mt-3 text-xl">
              <span className="mr-1 text-4xl font-bold tracking-tighter">
                {tv.vote_average}
              </span>
              <span className="relative -top-0.5">/</span>
              <span className="ml-1">10</span>
            </div>
          </div>
          <div className="w-full mt-8 ml-24">
            <header>
              <div className="flex items-end">
                <h1 className="text-3xl font-bold tracking-tighter text-center">{tv.name}</h1>
                <div className="relative ml-1 tracking-tighter text-center -top-0.5 text-1xl">({formatYear(tv.first_air_date)})</div>
              </div>
              <h3 className="font-bold text-gray-500">{tv.tagline}</h3>
            </header>
            <Meta item={tv} />
            <div className="mt-4 text-gray-600">{tv.overview}</div>

            <Credits credits={credits} />
          </div>
        </div>
      </main>
    </div>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: 'blocking'
  }
}

export const getStaticProps: GetStaticProps = async (context) => {
  const id = context?.params?.id;

  let [tvData, creditsData] = await Promise.all([
    fetch(`https://api.themoviedb.org/3/tv/${id}?api_key=e0c577647a14eae09f07aa14fee7caeb`),
    fetch(`https://api.themoviedb.org/3/tv/${id}/credits?api_key=e0c577647a14eae09f07aa14fee7caeb`)
  ]);

  const [tv, credits] = await Promise.all([tvData.json(), creditsData.json()]);
  return {
    props: {
      tv,
      credits
    },
  };
};

export default Movie