import Head from 'next/head'
import { InferGetStaticPropsType } from 'next'

import List from '../components/List'
import SiteHeader from '../components/SiteHeader'
import { formatMovie, formatTvShow, Movie, TvShow } from '../lib/helpers/format'
import Link from 'next/link'

const Home = ({ movies, tv }: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>NextJs Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto max-w-7xl">
        <div className="w-full mt-5 mb-10 text-right">
          <Link href="/login">
            <a className="font-bold text-orange-400 transition-all hover:text-black">Login</a>
          </Link></div>
        <SiteHeader />
        <List title="Today&apos;s trending movies" listData={movies} />
        <List title="Today&apos;s trending tv" listData={tv} />
      </main>
    </div>
  )
}

export async function getStaticProps() {
  let [moviesData, tvData] = await Promise.all([
    fetch('https://api.themoviedb.org/3/trending/movie/day?api_key=e0c577647a14eae09f07aa14fee7caeb'),
    fetch('https://api.themoviedb.org/3/trending/tv/day?api_key=e0c577647a14eae09f07aa14fee7caeb')
  ]);

  const [moviesRaw, tvRaw] = await Promise.all([moviesData.json(), tvData.json()]);
  const movies = moviesRaw.results.map((data: Movie) => formatMovie(data));
  const tv = tvRaw.results.map((data: TvShow) => formatTvShow(data));

  return {
    props: {
      movies,
      tv
    },
  }
}

export default Home

