import Head from 'next/head'
import { InferGetStaticPropsType } from 'next'
import List from '../components/List'
import SiteHeader from '../components/SiteHeader'
import { formatPerson, Person } from '../lib/helpers/format'

const Tv = ({ people }: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>NextJs Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto mt-10 max-w-7xl">
        <SiteHeader />
        <List title="Popular People" listData={people} />
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const results = await fetch('https://api.themoviedb.org/3/person/popular?api_key=e0c577647a14eae09f07aa14fee7caeb&page=1')
  const peopleData = await results.json();
  const people = peopleData.results.map((data: Person) => formatPerson(data));

  return {
    props: {
      people
    }
  }
}



export default Tv